# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CITpY95yyxlX6S9pbq9z_A-sFX5FrlLv
"""

import gradio as gr
from transformers import pipeline
import torch
import ast
import re
import black
import autopep8
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# Milestone 1: Configuration [cite: 292]
class ChatbotConfig:
    MODEL_NAME = "ibm-granite/granite-3.3-2b-instruct"
    DEFAULT_TEMP = 0.7
    DEFAULT_MAX_TOKENS = 256
    DEFAULT_TOP_P = 0.95

# Milestone 2: Code Analysis & Fixing Engine [cite: 303, 304, 305]
def detect_python_code(text):
    patterns = [
        r'def\s+\w+\s*\(',      # Functions
        r'class\s+\w+',         # Classes
        r'import\s+\w+',        # Imports
        r'if\s+.*:', r'for\s+.*' # Control flow
    ]
    return any(re.search(p, text) for p in patterns)

def check_syntax(code):
    try:
        ast.parse(code)
        return True, None
    except SyntaxError as e:
        return False, f"Syntax Error (line {e.lineno}): {e.msg}"

def fix_python_code(code):
    # Basic indentation and bracket fixing logic [cite: 305]
    try:
        # Use Black for professional formatting [cite: 306]
        fixed = black.format_str(code, mode=black.FileMode())
    except:
        # Fallback to autopep8 if Black fails [cite: 306]
        fixed = autopep8.fix_code(code)
    return fixed

# Milestone 3: Model Inference [cite: 41]
# Note: This will download a ~4GB model on first run
device = "cuda" if torch.cuda.is_available() else "cpu"
model_pipe = pipeline("text-generation", model=ChatbotConfig.MODEL_NAME, device=device)

conversation_history = []

def generate_response(user_message, temp, max_tokens, top_p):
    global conversation_history

    # Check if input is code to provide specific fixing [cite: 31]
    if detect_python_code(user_message):
        is_valid, error = check_syntax(user_message)
        if not is_valid:
            user_message = f"Fix this Python code and explain the error: {user_message}"

    conversation_history.append({"role": "user", "content": user_message})

    # Generate response from IBM Granite [cite: 41]
    output = model_pipe(
        user_message,
        max_new_tokens=int(max_tokens),
        temperature=temp,
        top_p=top_p,
        do_sample=True
    )

    assistant_text = output[0]['generated_text']
    conversation_history.append({"role": "assistant", "content": assistant_text})
    return assistant_text

# Milestone 4: Gradio Interface [cite: 42]
with gr.Blocks() as demo:
    gr.Markdown("# The Syntax Surgeon: AI Code Fixer")

    with gr.Row():
        with gr.Column(scale=4):
            chatbot = gr.Chatbot(height=400)
            msg = gr.Textbox(label="Enter code or questions here")
            submit = gr.Button("Send")

        with gr.Column(scale=1):
            temp_slider = gr.Slider(0.1, 1.0, value=0.7, label="Temperature")
            tokens_slider = gr.Slider(50, 1024, value=256, step=50, label="Max Tokens")
            top_p_slider = gr.Slider(0.1, 1.0, value=0.95, label="Top-P")
            clear = gr.ClearButton([msg, chatbot])

    def respond(message, history, temp, tokens, top_p):
        bot_message = generate_response(message, temp, tokens, top_p)
        history.append((message, bot_message))
        return "", history

    submit.click(respond, [msg, chatbot, temp_slider, tokens_slider, top_p_slider], [msg, chatbot])

demo.launch(share=True) # share=True creates a public URL [cite: 187, 193]
